
name: Run Tests
on: [push]
jobs:
  Run-Mistral-Tests:
    runs-on: self-hosted
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: Setting up Conda Environment
        run: |
          eval "$(conda 'shell.bash' 'hook' 2>/dev/null)" # make conda happy
          conda create -n mistral-${{github.sha}} python=3.8 pytorch torchdata cudatoolkit=10.2 -c pytorch
          conda activate mistral-${{github.sha}}
      - name: Installing dependencies
        run: pip install -r requirements.txt
      - name: Setting up environment variables
        run: |
          echo 'Deactivating wandb'
          cd tests ; wandb disabled
          echo 'MISTRAL_TEST_DIR:'
          echo $MISTRAL_TEST_DIR
      - name: Run tests (single node/single GPU)
        run: |
          cd tests
          CUDA_VISIBLE_DEVICES=0 pytest --durations=0
      - name: Delete conda environment
        if: always()
        run: |
          conda deactivate
          conda env remove -n mistral-${{github.sha}}
      - run: echo "All tests finished!"
      - run: echo "🍏 This job's status is ${{ job.status }}."
